import = ["/home/matteo/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
decorations_theme_variant = "None"
dynamic_title = true
opacity = 1

[window.padding]
x = 3
y = 3
